import bs4
import requests
from bs4 import BeautifulSoup
import sys
import os
import time
import asyncio

sys.stdout = open(sys.stdout.fileno(), mode='w', encoding='utf-8', buffering=1)

async def get_lyrics(song_title, artist_name, access_token):
    base_url = "https://api.genius.com/"
    headers = {'Authorization': 'Bearer ' + access_token}
    search_url = base_url + "search"
    data = {'q': song_title + ' ' + artist_name}
    response = requests.get(search_url, data=data, headers=headers)
    json = response.json()
    remote_song_info = None
    for hit in json["response"]["hits"]:
        if artist_name.lower() in hit["result"]["primary_artist"]["name"].lower():
            remote_song_info = hit
            break
    if remote_song_info:
        song_api_path = remote_song_info["result"]["api_path"]
        song_url = base_url + song_api_path
        song_response = requests.get(song_url, headers=headers)
        song_json = song_response.json()
        path = song_json["response"]["song"]["path"]
        lyrics_url = "https://genius.com" + path
        page = requests.get(lyrics_url)
        soup = BeautifulSoup(page.text, 'html.parser')

        for br in soup.find_all("br"):
             br.replace_with("\n")

        lyrics_elements = soup.select('[data-lyrics-container="true"]')
        lyrics = ""
        for le in lyrics_elements:
            lyrics += le.get_text(strip=False)

        return lyrics
    else:
        return None
    
   
songs = [
("50 Cent","In Da Club"),
("Adele","Chasing Pavements"),
("Adele","Hello"),
("Adele","Rolling In The Deep"),
("Adele","Set Fire To The Rain"),
("Adele","Someone Like You"),
("Aerosmith","Walk This Way"),
("Akon","Don't Matter"),
("Akon","Lonely"),
("Akon","Smack That"),
("Al Green","Let's Stay Together"),
("Al Green","Love and Happiness"),
("Al Green","Take Me to the River"),
("Al Green","Tired of Being Alone"),
("Alice Cooper","I'm Eighteen"),
("Alice Cooper","School's Out"),
("Alicia Keys","Fallin'"),
("Alicia Keys","No One"),
("Amy Winehouse","Rehab"),
("Anna and the Barbies","Márti dala"),
("Anna and the Barbies","Négykézláb"),
("Anna and the Barbies","Utópia"),
("Archie Bell and the Drells","Tighten Up"),
("Aretha Franklin","Chain of Fools"),
("Aretha Franklin","Do Right Woman, Do Right Man"),
("Aretha Franklin","Respect"),
("Ariana Grande","7 Rings"),
("Ariana Grande","Break Free"),
("Ariana Grande","No Tears Left To Cry"),
("Ariana Grande","Side To Side"),
("Ariana Grande","Thank U Next"),
("AWS","Viszlát nyár"),
("Azahriah","3Korty"),
("Azahriah","4K Love"),
("Azahriah","aight"),
("Azahriah","angel dust"),
("Azahriah","blvck"),
("Azahriah","Bulbaba (ft. Desh)"),
("Azahriah","Béke (ft. Desh, Lord panamo, Youngfly, Copy con)"),
("Azahriah","Casa de papel"),
("Azahriah","Ceremónia (ft. Desh)"),
("Azahriah","cipoe (full)"),
("Azahriah","cipoe"),
("Azahriah","Delirium"),
("Azahriah","Depicentrum (outro)"),
("Azahriah","Dopamin (ft. Desh)"),
("Azahriah","Drogba (ft. Desh)"),
("Azahriah","El Barto (ft. Desh)"),
("Azahriah","emulator"),
("Azahriah","Felednéd (ft. Desh)"),
("Azahriah","Figyelj"),
("Azahriah","filter"),
("Azahriah","Four moods 2 (ft. Queen Omega)"),
("Azahriah","Four Moods"),
("Azahriah","Gát"),
("Azahriah","Habibi (ft. Desh)"),
("Azahriah","Heaven (ft. Stadiumx, Sam Martin)"),
("Azahriah","Hessdalen"),
("Azahriah","Introvertált dal"),
("Azahriah","Kaotikus egy ház!"),
("Azahriah","kapu"),
("Azahriah","lesson"),
("Azahriah","mariana.árok"),
("Azahriah","Miafasz (ft. Desh)"),
("Azahriah","middle door"),
("Azahriah","Mind1 (ft. Desh)"),
("Azahriah","Okari"),
("Azahriah","press f (interlude)"),
("Azahriah","prior"),
("Azahriah","Pullup (ft. Desh)"),
("Azahriah","quasar"),
("Azahriah","rec (bonus track)"),
("Azahriah","rip gemini, pt. 2"),
("Azahriah","rip gemini"),
("Azahriah","Rét (ft. Desh)"),
("Azahriah","Rút"),
("Azahriah","Silbak Intro"),
("Azahriah","szosziazi"),
("Azahriah","tartarosz"),
("Azahriah","tevagyazalány (ft. Desh)"),
("Azahriah","Tisztán iszom (ft. Desh)"),
("Azahriah","Téveszmék"),
("Azahriah","Valami Amerikai"),
("Azahriah","viadal"),
("Azahriah","Vicc (ft. Desh)"),
("Azahriah","yellow card"),
("Azahriah","Yesterday"),
("Azahriah","yukuta"),
("Bagossy Brothers Company","Valahol itt"),
("Bagossy Brothers Company","Van ez a hely"),
("Barrett Strong","Money (That's What I Want)"),
("BBNO$","Bad Boy"),
("BBNO$","Bunk"),
("BBNO$","Gone"),
("BBNO$","Help Herself"),
("BBNO$","Jack Money Bean"),
("BBNO$","Lalala"),
("BBNO$","Nursery"),
("BBNO$","On God"),
("BBNO$","Pouch"),
("BBNO$","Shining On My Ex"),
("BBNO$","Slop"),
("BBNO$","Stucco"),
("BBNO$","Tennis Ball"),
("BBNO$","Who Dat Boy"),
("BBNO$","Y2K"),
("Beastie Boys","Sabotage"),
("Beck","Loser"),
("Belga","Az a baj"),
("Belmondo","Lesz, volt, van"),
("Ben E. King","Spanish Harlem"),
("Beyonce","Crazy In Love"),
("Beyonce","Formation"),
("Beyonce","Halo"),
("Beyonce","Irreplaceable"),
("Beyonce","Single Ladies"),
("Big Brother and the Holding Company","Piece of My Heart"),
("Bill Withers","Ain't No Sunshine"),
("Billie Eilish","Bad Guy"),
("Billie Eilish","Bury A Friend"),
("Billie Eilish","Copycat"),
("Billie Eilish","Everything I Wanted"),
("Billie Eilish","Happier Than Ever"),
("Billie Eilish","I Love You"),
("Billie Eilish","Idontwannabeyouanymore"),
("Billie Eilish","Lovely"),
("Billie Eilish","My Future"),
("Billie Eilish","No Time to Die"),
("Billie Eilish","Ocean Eyes"),
("Billie Eilish","Therefore I Am"),
("Billie Eilish","When The Party's Over"),
("Billie Eilish","You Should See Me in a Crown"),
("Billie Eilish","Your Power"),
("Black Sabbath","Iron Man"),
("Black Sabbath","Paranoid"),
("Blahalouisiana","Hol van az a lány"),
("Blahalouisiana","Talált tenger"),
("Blondie","Call Me"),
("Blondie","Heart of Glass"),
("Blondie","One Way or Another"),
("Bo Diddley","Bo Diddley"),
("Bob Dylan","Blowin' in the Wind"),
("Bob Dylan","Highway 61 Revisited"),
("Bob Dylan","Like a Rolling Stone"),
("Bob Dylan","Mr. Tambourine Man"),
("Bob Dylan","Subterranean Homesick Blues"),
("Bob Dylan","Tangled Up in Blue"),
("Bob Dylan","The Times They Are A-Changin'"),
("Bob Marley and the Wailers","Get Up, Stand Up"),
("Bob Marley and the Wailers","No Woman, No Cry"),
("Bob Marley and the Wailers","Redemption Song"),
("Bob Marley and the Whailers","I Shot the Sheriff"),
("Bobby Darin","Mack the Knife"),
("Bogi","We All"),
("Bonnie Raitt","I Can't Make You Love Me"),
("Boston","More Than a Feeling"),
("Britney Spears","Oops!...I Did It Again"),
("Britney Spears","Toxic"),
("Brook Benton","Rainy Night in Georgia"),
("Bruce Springsteen","Born in the U.S.A."),
("Bruce Springsteen","Born to Run"),
("Bruce Springsteen","Thunder Road"),
("Bruno Mars","Grenade"),
("Bruno Mars","Just The Way You Are"),
("Bruno Mars","Locked Out Of Heaven"),
("Bruno Mars","Treasure"),
("Bruno Mars","Uptown Funk"),
("Bródy János","Mit tehetnék érted"),
("Buddy Holly and the Crickets","Not Fade Away"),
("Buddy Holly and the Crickets","That'll Be the Day"),
("Buffalo Springfield","For What It's Worth"),
("ByeAlex és a Slepp","Babylon"),
("ByeAlex és a Slepp","Hé Budapest!"),
("ByeAlex és a Slepp","Menned kéne"),
("Bëlga","Az a baj"),
("Caramel","Lélekdonor"),
("Caramel","Vízió"),
("Carl Perkins","Blue Suede Shoes"),
("Carole King","It's Too Late"),
("Carson Coma","Belenéz"),
("Carson Coma","Bezár a bazár"),
("Carson Coma","Corduroy Club"),
("Carson Coma","Feketemosó"),
("Carson Coma","Háború és béke"),
("Carson Coma","Hé, Magány!"),
("Carson Coma","Indulj el"),
("Carson Coma","Kortárs"),
("Carson Coma","Meggondolatlan irónia"),
("Carson Coma","Song About My Grandma"),
("Cheap Trick","Surrender"),
("Chic","Good Times"),
("Children of Distance","Emlékezz rám"),
("Children of Distance","Sajnálom"),
("Chubby Checker","The Twist"),
("Chuck Berry","Johnny B. Goode"),
("Chuck Berry","Maybellene"),
("Chuck Berry","Roll Over Beethoven"),
("Chuck Berry","Sweet Little Sixteen"),
("Coldplay","Adventure Of A Lifetime"),
("Coldplay","Clocks"),
("Coldplay","Fix You"),
("Coldplay","Paradise"),
("Coldplay","Viva La Vida"),
("Compact Disco","Sound of Our Hearts"),
("Cream","Sunshine of Your Love"),
("Creedence Clearwater Revival","Bad Moon Rising"),
("Creedence Clearwater Revival","Fortunate Son"),
("Creedence Clearwater Revival","Who'll Stop the Rain"),
("Daft Punk","Around the World"),
("Daft Punk","Da Funk"),
("Daft Punk","Digital Love"),
("Daft Punk","Get Lucky"),
("Daft Punk","Harder, Better, Faster, Stronger"),
("Daft Punk","Human After All"),
("Daft Punk","Instant Crush"),
("Daft Punk","Lose Yourself to Dance"),
("Daft Punk","One More Time"),
("Daft Punk","Robot Rock"),
("Daft Punk","Something About Us"),
("Daft Punk","Technologic"),
("Daft Punk","Touch"),
("Daniel Powter","Bad Day"),
("David Bowie","Heroes"),
("David Bowie","Young Americans"),
("David Bowie","Ziggy Stardust"),
("David Guetta","Sexy Chick - featuring Akon"),
("Del Shannon","Runaway"),
("Derek and the Dominos","Layla"),
("Destiny's Child","Lose My Breath"),
("Dido","White Flag"),
("Dion","Runaround Sue"),
("Dionne Warwick","Walk On By"),
("Dolly Parton","Jolene"),
("Donna Summer","Hot Stuff"),
("Dr. Dre and 2Pac","California Love"),
("Drake","God's Plan"),
("Drake","Hold On, We're Going Home"),
("Drake","Hotline Bling"),
("Drake","In My Feelings"),
("Drake","One Dance"),
("Duffy","Mercy"),
("Dusty Springfield","You Don't Have to Say You Love Me"),
("Dzsúdló","Lej"),
("Eamon","Fuck It (I Don't Want You Back)"),
("Earth, Wind and Fire","That's the Way of the World"),
("Ed Sheeran","Castle On The Hill"),
("Ed Sheeran","Perfect"),
("Ed Sheeran","Photograph"),
("Ed Sheeran","Shape Of You"),
("Ed Sheeran","Thinking Out Loud"),
("Eddie Cochran","Summertime Blues"),
("Elefánt","Olyan éj"),
("Elton John","Candle in the Wind"),
("Elton John","Tiny Dancer"),
("Elvis Costello","Alison"),
("Elvis Costello","Watching the Detectives"),
("Elvis Presley","A Little Less Conversation (JXL Radio Edit Remix)"),
("Elvis Presley","All Shook Up"),
("Elvis Presley","Heartbreak Hotel"),
("Elvis Presley","Hound Dog"),
("Elvis Presley","Jailhouse Rock"),
("Elvis Presley","Mystery Train"),
("Elvis Presley","Suspicious Minds"),
("Elvis Presley","That's All Right"),
("Eminem","8 Mile"),
("Eminem","Beautiful"),
("Eminem","Berzerk"),
("Eminem","Cleanin' Out My Closet"),
("Eminem","Guilty Conscience"),
("Eminem","Just Lose It"),
("Eminem","Killshot"),
("Eminem","Like Toy Soldiers"),
("Eminem","Lose Yourself"),
("Eminem","Love The Way You Lie"),
("Eminem","Mockingbird"),
("Eminem","My Name Is"),
("Eminem","No Love"),
("Eminem","Not Afraid"),
("Eminem","Rap God"),
("Eminem","Sing for the Moment"),
("Eminem","Space Bound"),
("Eminem","Stan"),
("Eminem","Survival"),
("Eminem","The Real Slim Shady"),
("Eminem","The Way I Am"),
("Eminem","Till I Collapse"),
("Eminem","We Made You"),
("Eminem","When I'm Gone"),
("Eminem","Without Me"),
("Eminem featuring Dido","Stan"),
("Enrique Iglesias","Hero"),
("Eric B and Rakim","I Know You Got Soul"),
("Eric Clapton","Tears in Heaven"),
("Esti Kornél","Boldogság te kurva"),
("Eurythmics","Sweet Dreams (Are Made of This)"),
("Evanescence","Bring Me To Life"),
("Fats Domino","Blueberry Hill"),
("Fergie","Big Girls Don't Cry"),
("Fleetwood Mac","Go Your Own Way"),
("Fleetwood Mac","Rhiannon (Will You Ever Win)"),
("Flo Rida","Low (Feat. T-Pain) (Album Version)"),
("Flo Rida","Right Round"),
("Follow The Flow","Anyám mondta"),
("Follow The Flow","Csak nélküled élem túl"),
("Follow The Flow","Maradok távol"),
("Follow The Flow","Nem tudja senki"),
("Follow The Flow","Porszem"),
("Follow The Flow","Régi mese"),
("Foreigner","I Want to Know What Love Is"),
("Frankie Lymon and the Teenagers","Why Do Fools Fall In Love"),
("Funkadelic","One Nation Under a Groove"),
("Ganxsta Zolee és a Kartel","Tedd fel"),
("Gene Vincent and His Blue Caps","Be-Bop-A-Lula"),
("George Harrison","My Sweet Lord"),
("George Jones","He Stopped Loving Her Today"),
("Glen Campbell","By the Time I Get to Phoenix"),
("Gloria Gaynor","I Will Survive"),
("Grandmaster Flash and the Furious Five","The Message"),
("Green Day","Boulevard Of Broken Dreams"),
("Guns n' Roses","Paradise City"),
("Guns n' Roses","Welcome to the Jungle"),
("Gwen Stefani","Hollaback Girl"),
("Gwen Stefani","The Sweet Escape"),
("Halott Pénz","Darabokra törted a szívem"),
("Halott Pénz","Otthon"),
("Halott Pénz","Szólj anyunak, hogy a városba' vagyok"),
("Halott Pénz feat. Dér Heni","Élnünk kellett volna"),
("Hank Williams","I'm So Lonesome I Could Cry"),
("Heaven Street Seven","Ez a szerelem"),
("Honeybeast","Bódottá"),
("Honeybeast","Lélekdonor"),
("Honeybeast","Maradok"),
("Honeybeast","Így játszom"),
("Howlin' Wolf","Smoke Stack Lightning"),
("Howlin' Wolf","Spoonful"),
("Ike and Tina Turner","River Deep - Mountain High"),
("Imagine Dragons","Amsterdam"),
("Imagine Dragons","Bad Liar"),
("Imagine Dragons","Believer"),
("Imagine Dragons","Demons"),
("Imagine Dragons","Gold"),
("Imagine Dragons","I Bet My Life"),
("Imagine Dragons","It's Time"),
("Imagine Dragons","Natural"),
("Imagine Dragons","On Top of the World"),
("Imagine Dragons","Radioactive"),
("Imagine Dragons","Shots"),
("Imagine Dragons","Thunder"),
("Imagine Dragons","Walking the Wire"),
("Imagine Dragons","Whatever It Takes"),
("Imagine Dragons","Zero"),
("Ivan & The Parazol","Take My Hand"),
("Jackie Wilson","(Your Love Keeps Lifting Me) Higher and Higher"),
("Jackie Wilson","Lonely Teardrops"),
("Jackson Browne","Running on Empty"),
("James Brown","Get Up (I Feel Like Being a) Sex Machine"),
("James Brown","I Got You (I Feel Good)"),
("James Brown","Papa's Got a Brand New Bag"),
("James Brown","Say It Loud, I'm Black and Proud"),
("James Taylor","Fire and Rain"),
("Jason Mraz","I'm Yours"),
("Jeff Buckley","Hallelujah"),
("Jefferson Airplane","Somebody to Love"),
("Jefferson Airplane","White Rabbit"),
("Jennifer Lopez","Love Don't Cost a Thing"),
("Jerry Butler and the Impressions","For Your Precious Love"),
("Jerry Lee Lewis","Great Balls of Fire"),
("Jerry Lee Lewis","Whole Lotta Shakin' Goin On"),
("Jimi Hendrix","All Along the Watchtower"),
("Jimi Hendrix","Little Wing"),
("Jimi Hendrix","Purple Haze"),
("Jimi Hendrix","Voodoo Child (Slight Return)"),
("Jimmy Cliff","Many Rivers to Cross"),
("Jimmy Cliff","The Harder They Come"),
("Joan Jett","I Love Rock 'N Roll"),
("John Cougar Mellencamp","Pink Houses"),
("John Lee Hooker","Boom Boom"),
("John Lennon","Imagine"),
("Johnny Cash","I Walk the Line"),
("Johnny Cash","Ring of Fire"),
("Joni Mitchell","Free Man in Paris"),
("Joni Mitchell","Help Me"),
("Jordin Sparks","No Air duet with Chris Brown"),
("Justin Bieber","Baby"),
("Justin Bieber","Love Yourself"),
("Justin Bieber","Sorry"),
("Justin Bieber","What Do You Mean"),
("Justin Timberlake","SexyBack"),
("Kanye West","Gold Digger"),
("Kanye West","Stronger"),
("Katy Perry","California Gurls"),
("Katy Perry","Dark Horse"),
("Katy Perry","Firework"),
("Katy Perry","Hot N Cold"),
("Katy Perry","I Kissed a Girl"),
("Katy Perry","Roar"),
("Katy Perry","Teenage Dream"),
("KFT","Balatoni nyár"),
("Kid Rock","All Summer Long"),
("Kiscsillag","Ha én lennék"),
("Konyha","Százszor visszajátszott"),
("Kowalsky meg a Vega","Amilyen hülye vagy, úgy szeretlek"),
("Kowalsky meg a Vega","Egy világon át"),
("Kowalsky meg a Vega","Tombold ki"),
("Krúbi","Krúbi Interjú"),
("Krúbi","Nehézlábérzés"),
("Krúbi","Partyzán"),
("Krúbi","Schmuck"),
("Krúbi","Szív"),
("Krúbi","Zárolás Feloldva"),
("Kállay Saunders András","Running"),
("Labelle","Lady Marmalade"),
("Lady Gaga","Bad Romance"),
("Lady Gaga","Born This Way"),
("Lady Gaga","Just Dance"),
("Lady Gaga","Poker Face"),
("Lady Gaga","Telephone"),
("Lavern Baker","Jim Dandy"),
("LeAnn Rimes","Can't Fight The Moonlight"),
("Led Zeppelin","Black Dog"),
("Led Zeppelin","Heartbreaker"),
("Led Zeppelin","Stairway To Heaven"),
("Led Zeppelin","Whole Lotta Love"),
("Leona Lewis","Bleeding Love"),
("Lifehouse","Hanging By A Moment"),
("Little Eva","The Locomotion"),
("Little Richard","Good Golly, Miss Molly"),
("Little Richard","Keep a Knockin'"),
("Little Richard","Long Tall Sally"),
("Little Richard","Tutti-Frutti"),
("Lloyd Price","Stagger Lee"),
("Lóci Játszik","Nem táncolsz jobban"),
("Madonna","4 Minutes (feat. Justin Timberlake and Timbaland)"),
("Madonna","Like a Prayer"),
("Magna Cum Laude","Színezd újra"),
("Magna Cum Laude","Vidéki sanzon"),
("Majka","Mindenki táncol 90'"),
("Majka & Curtis","Belehalok"),
("Majka & Curtis","Eléglesz"),
("Majka & Curtis","Füttyös"),
("Majka & Curtis & BLR","Belehalok"),
("Majka & Pápai Joci","Nélküled"),
("Margaret Island","Hóvirág"),
("Margaret Island","Járatlan úton"),
("Margaret Island","Nem voltál jó"),
("Mariah Carey","We Belong Together"),
("Mario","Let Me Love You"),
("Maroon 5","Girls Like You"),
("Maroon 5","Moves Like Jagger"),
("Maroon 5","Payphone"),
("Maroon 5","She Will Be Loved"),
("Maroon 5","Sugar"),
("Martha and the Vandellas","Dancing in the Street"),
("Martha and the Vandellas","Nowhere to Run"),
("Marvin Gaye","I Heard It Through the Grapevine"),
("Marvin Gaye","What's Going On"),
("Michael Jackson","Beat It"),
("Michael Jackson","Billie Jean"),
("Mott the Hoople","All the Young Dudes"),
("Muddy Waters","Got My Mojo Working"),
("Muddy Waters","Hoochie Coochie Man"),
("Muddy Waters","Rollin' Stone"),
("N.W.A","Fuck tha Police"),
("Neil Young","Cortez the Killer"),
("Neil Young","Heart of Gold"),
("Nelly Furtado","Promiscuous"),
("Nelly Furtado","Say It Right"),
("New Level Empire","Son of the Sun"),
("New Order","Bizarre Love Triangle"),
("New York Dolls","Personality Crisis"),
("Nicki Minaj","Anaconda"),
("Nicki Minaj","Bang Bang"),
("Nicki Minaj","Pound The Alarm"),
("Nicki Minaj","Starships"),
("Nicki Minaj","Super Bass"),
("Nirvana","All Apologies"),
("Nirvana","Come As You Are"),
("Nirvana","Smells Like Teen Spirit"),
("Norman Greenbaum","Spirit in the Sky"),
("Ocho Macho","Nagy világnak"),
("Odett","Feketén a hófehér"),
("Odett","Van az úgy"),
("Otis Redding","(Sittin on) the Dock of the Bay"),
("Otis Redding","I've Been Loving You Too Long (to Stop Now)"),
("OutKast","Hey Ya!"),
("OutKast","Ms. Jackson"),
("PASO","This is my life"),
("Patsy Cline","Crazy"),
("Patti Smith Group","Dancing Barefoot"),
("Paul McCartney","Maybe I'm Amazed"),
("Paul Simon","Graceland"),
("Pavement","Summer Babe"),
("Percy Sledge","When a Man Loves a Woman"),
("Pink Ball","So What"),
("Pink Floyd","Another Brick in the Wall, Part 2"),
("Pink Floyd","Brain Damage"),
("Pink Floyd","Comfortably Numb"),
("Pink Floyd","Eclipse"),
("Pink Floyd","Hey You"),
("Pink Floyd","High Hopes"),
("Pink Floyd","Learning to Fly"),
("Pink Floyd","Money"),
("Pink Floyd","Mother"),
("Pink Floyd","On the Turning Away"),
("Pink Floyd","Shine On You Crazy Diamond"),
("Pink Floyd","The Great Gig in the Sky"),
("Pink Floyd","Time"),
("Pink Floyd","Us and Them"),
("Pink Floyd","Wish You Were Here"),
("Plain White T's","Hey There Delilah"),
("Post Malone","Better Now"),
("Post Malone","Circles"),
("Post Malone","Congratulations"),
("Post Malone","Rockstar"),
("Post Malone","Sunflower"),
("Prince","Little Red Corvette"),
("Prince","Sign 'O' the Times"),
("Prince","When Doves Cry"),
("Procol Harum","Whiter Shade of Pale"),
("Public Enemy","Fight the Power"),
("Punnany Massif","Láv"),
("Punnany Massif","Másfél hete"),
("Péter Szabó Szilvia","Búcsú"),
("Péter Szabó Szilvia","Hív a végtelen"),
("Péter Szabó Szilvia","Nem adom fel"),
("Péter Szabó Szilvia","Álmodj velem"),
("Péterfy Bori & Love Band","Hajolj bele a hajamba"),
("Queen","We Will Rock You"),
("Quimby","Autó egy szerpentinen"),
("Quimby","Hajnali párna"),
("Quimby","Most múlik pontosan"),
("Quimby","Sehol se talállak"),
("R. Kelly","Ignition"),
("Radics Gigi","Ne félj"),
("Radics Gigi","Álmodj velem"),
("Radics Gigi","Úgy fáj"),
("Radiohead","Paranoid Android"),
("Ramones","Blitzkrieg Bop"),
("Ramones","Sheena Is a Punk Rocker"),
("Randy Newman","Sail Away"),
("Ray Charles","Georgia on My Mind"),
("Ray Charles","What'd I Say"),
("Rick James","Super Freak"),
("Rihanna","Diamonds"),
("Rihanna","Disturbia"),
("Rihanna","Don't Stop The Music"),
("Rihanna","Only Girl (In The World)"),
("Rihanna","Rude Boy"),
("Rihanna","Take A Bow"),
("Rihanna","Umbrella"),
("Rihanna","We Found Love"),
("Ritchie Valens","La Bamba"),
("Roberta Flack","Killing Me Softly With His Song"),
("Roy Orbison","Crying"),
("Roy Orbison","In Dreams"),
("Roy Orbison","Oh, Pretty Woman"),
("Run-DMC","Walk This Way"),
("Rúzsa Magdolna","Egyszer"),
("Rúzsa Magdolna","Engedj el"),
("Rúzsa Magdolna","Gábriel"),
("Rúzsa Magdolna","Lesz, ahogy lesz"),
("Rúzsa Magdolna","Szerelem"),
("Rúzsa Magdolna","Tudom, hogy van"),
("Rúzsa Magdolna","Éden"),
("Salt-n-Pepa","Push It"),
("Sam and Dave","Soul Man"),
("Sam Cooke","A Change Is Gonna Come"),
("Sam Cooke","Cupid"),
("Sam Cooke","You Send Me"),
("Sam Smith","I'm Not The Only One"),
("Sam Smith","Lay Me Down"),
("Sam Smith","Stay With Me"),
("Sam Smith","Too Good At Goodbyes"),
("Sam Smith","Writing's On The Wall"),
("Santana","Maria Maria"),
("Screamin' Jay Hawkins","I Put a Spell on You"),
("Sean Kingston","Beautiful Girls"),
("Shaggy","Angel"),
("Shaggy","It Wasn't Me"),
("Shakira","Hips Don't Lie (feat. Wyclef Jean)"),
("Shawn Mendes","Mercy"),
("Shawn Mendes","Senorita"),
("Shawn Mendes","Stitches"),
("Shawn Mendes","There's Nothing Holdin' Me Back"),
("Shawn Mendes","Treat You Better"),
("Simon and Garfunkel","Bridge Over Troubled Water"),
("Simon and Garfunkel","The Boxer"),
("Simon and Garfunkel","The Sounds of Silence"),
("Sly and the Family Stone","Hot Fun in the Summertime"),
("Smokey Robinson","Ooo Baby Baby"),
("Smokey Robinson and the Miracles","Shop Around"),
("Smokey Robinson and the Miracles","The Tracks of My Tears"),
("Sonny and Cher","I Got You Babe"),
("Soulwave","Hétköznapi"),
("Soulwave","Kalandor"),
("Stevie Wonder","Higher Ground"),
("Stevie Wonder","Living for the City"),
("Stevie Wonder","Superstition"),
("Stevie Wonder","You Are the Sunshine of My Life"),
("Szeder","Reggeli dal"),
("Tankcsapda","Ez az a ház"),
("Tankcsapda","Mennyország tourist"),
("Taylor Swift","Blank Space"),
("Taylor Swift","Love Story"),
("Taylor Swift","Shake It Off"),
("Taylor Swift","We Are Never Ever Getting Back Together"),
("Taylor Swift","You Belong With Me"),
("The Animals","Don't Let Me Be Misunderstood"),
("The Band","The Weight"),
("The Beach Boys","California Girls"),
("The Beach Boys","God Only Knows"),
("The Beach Boys","Good Vibrations"),
("The Beach Boys","In My Room"),
("The Beach Boys","Sloop John B"),
("The Beatles","A Day in the Life"),
("The Beatles","All You Need Is Love"),
("The Beatles","Can't Buy Me Love"),
("The Beatles","Help!"),
("The Beatles","Hey Jude"),
("The Beatles","I Want to Hold Your Hand"),
("The Beatles","In My Life"),
("The Beatles","Let It Be"),
("The Beatles","Norwegian Wood (This Bird Has Flown)"),
("The Beatles","Rain"),
("The Beatles","She Loves You"),
("The Beatles","Something"),
("The Beatles","Strawberry Fields Forever"),
("The Beatles","With a Little Help From My Friends"),
("The Beatles","Yesterday"),
("The Biebers","Sorry"),
("The Black Eyed Peas","Boom Boom Pow"),
("The Black Eyed Peas","Don't Phunk With My Heart"),
("The Black Eyed Peas","I Gotta Feeling"),
("The Black Eyed Peas","Shut Up"),
("The Box Tops","The Letter"),
("The Byrds","Mr. Tambourine Man"),
("The Chiffons","One Fine Day"),
("The Clash","Complete Control"),
("The Clash","London Calling"),
("The Clash","Should I Stay or Should I Go"),
("The Clash","Train in Vain"),
("The Crystals","Da Doo Ron Ron (When He Walked Me Home)"),
("The Crystals","He's a Rebel"),
("The Crystals","Then He Kissed Me"),
("The Cure","Just Like Heaven"),
("The Cure","Pictures of You"),
("The Del-Vikings","Come Go With Me"),
("The Dells","Oh, What a Night"),
("The Dixie Cups","Chapel of Love"),
("The Doors","Light My Fire"),
("The Doors","The End"),
("The Drifters","Money Honey"),
("The Drifters","Up on the Roof"),
("The Eagles","Desperado"),
("The Eagles","Hotel California"),
("The Everly Brothers","Bye Bye Love"),
("The Everly Brothers","Wake Up Little Susie"),
("The Family Stone","Dance to the Music"),
("The Five Satins","In the Still of the Nite"),
("The Four Tops","Reach Out, I'll Be There"),
("The Four Tops","Standing in the Shadows of Love"),
("The Fray","How to Save a Life"),
("The Impressions","People Get Ready"),
("The Isley Brothers","Shout (Parts 1 and 2)"),
("The Isley Brothers","That Lady (Part 1 and 2)"),
("The Jackson 5","I Want You Back"),
("The Jam","That's Entertainment"),
("The Kingsmen","Louie Louie"),
("The Kinks","Waterloo Sunset"),
("The Kinks","You Really Got Me"),
("The Left Banke","Walk Away Renee"),
("The Mamas and The Papas","California Dreamin'"),
("The Modern Lovers","Roadrunner"),
("The Platters","The Great Pretender"),
("The Police","Every Breath You Take"),
("The Righteous Brothers","You've Lost That Lovin' Feelin'"),
("The Rolling Stones","Brown Sugar"),
("The Rolling Stones","Gimme Shelter"),
("The Rolling Stones","Honky Tonk Women"),
("The Rolling Stones","Miss You"),
("The Rolling Stones","Ruby Tuesday"),
("The Rolling Stones","Satisfaction"),
("The Rolling Stones","Street Fighting Man"),
("The Rolling Stones","Sympathy for the Devil"),
("The Rolling Stones","Wild Horses"),
("The Rolling Stones","You Can't Always Get What You Want"),
("The Ronettes","Be My Baby"),
("The Ronettes","Walking in the Rain"),
("The Sex Pistols","Anarchy in the U.K."),
("The Shangri-Las","Leader of the Pack"),
("The Staple Singers","I'll Take You There"),
("The Stooges","I Wanna Be Your Dog"),
("The Stooges","Search and Destroy"),
("The Sugarhill Gang","Rappers Delight"),
("The Supremes","Baby Love"),
("The Supremes","Where Did Our Love Go"),
("The Supremes","You Keep Me Hanging On"),
("The Temptations","My Girl"),
("The Troggs","Wild Thing"),
("The Velvet Underground","Heroin"),
("The Velvet Underground","Sweet Jane"),
("The Weeknd","Blinding Lights"),
("The Weeknd","Can't Feel My Face"),
("The Weeknd","I Feel It Coming"),
("The Weeknd","Save Your Tears"),
("The Weeknd","Starboy"),
("The Weeknd","The Hills"),
("The Who","Baba O'Riley"),
("The Who","I Can See for Miles"),
("The Who","My Generation"),
("The Young Rascals","Good Lovin'"),
("The Zombies","She's Not There"),
("Them","Gloria"),
("Thin Lizzy","The Boys Are Back in Town"),
("Timbaland","The Way I Are"),
("Tina Turner","What's Love Got To Do With It"),
("Toot and the Maytals","Pressure Drop"),
("Tujamo","Boneless"),
("Tujamo","Booty Bounce"),
("Tujamo","California"),
("Tujamo","Candy on the Dancefloor"),
("Tujamo","Drop That Low (When I Dip)"),
("Tujamo","Get Up"),
("Tujamo","Hell Yeah"),
("Tujamo","Hey Mister"),
("Tujamo","La Vida"),
("Tujamo","Lonely"),
("Tujamo","Make U Love Me"),
("Tujamo","One on One"),
("Tujamo","Say What You Wanna"),
("Tujamo","Who"),
("Tujamo","With U"),
("U2","I Still Haven't Found What I'm Looking For"),
("U2","One"),
("U2","Sunday Bloody Sunday"),
("Usher","Yeah!"),
("Vad Fruttik","Embergép"),
("Vad Fruttik","Lehetek én is"),
("Vad Fruttik","Nekem senkim sincsen"),
("Vad Fruttik","Sárga Zsiguli"),
("Valmar","Úristen"),
("Van Morrison","Brown Eyed Girl"),
("Van Morrison","Into the Mystic"),
("Van Morrison","Moondance"),
("Vanessa Carlton","A Thousand Miles"),
("Varga Viktor","Lehet zöld az ég"),
("Weezer","Buddy Holly"),
("Wellhello","Apu vedd meg"),
("Wellhello","Emlékszem, Sopronban"),
("Wellhello","Odaút"),
("Wellhello","Rakpart"),
("Wellhello","Sokszor volt már így"),
("Willie Nelson","Blue Eyes Crying In the Rain"),
("Willie Nelson","On the Road Again"),
("Zséda","Legyen úgy"),
("Ákos","Ilyenek voltunk"),
("Ákos","Keresem az utam"),
("Ákos","Ugyanúgy"),
]


set_songs = set(songs)

access_token = 'Your Access Token Here'

async def fetch_lyrics(artist_name, song_name, access_token):
    lyrics = await get_lyrics(song_name, artist_name, access_token)
    return lyrics

async def getSong():
    for song in set_songs:
        existingpath = f"songs/{song[0]}/{song[1]}.txt"
         # Check if the file already exists
        if os.path.exists(existingpath):
            print(f"Skipping {song[0]} - {song[1]}")
            continue

        lyrics = await fetch_lyrics(song[0], song[1], access_token)    
        await asyncio.sleep(1) 
        # Extract artist name and song name
        artist_name = song[0]
        song_name = song[1]

        # Create the directory path
        directory_path = f"songs/{artist_name}"
        if not os.path.exists(directory_path):
            os.makedirs(directory_path, exist_ok=True)

        # Create the file path
        # Create the file path
        file_path = f"{directory_path}/{song_name}.txt"
        
        # Write the lyrics to the file
        with open(file_path, 'w', encoding=sys.stdout.encoding, errors='replace') as file:
            if(lyrics is not None):
                file.write(lyrics)
                print (f"Lyrics for {song[0]} - {song[1]} saved")
                #print ("saved a song")

    
    #print(lyrics.encode(sys.stdout.encoding, errors='replace'))



async def main():
    await getSong()

asyncio.run(main())
